### ISSUE TITLE
Duplicate feedstock

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/trio-asyncio-feedstock#12]
This feedstock is essentially a duplicate repo for https://github.com/conda-forge/trio_asyncio-feedstock. Looking at the creation dates:

* conda-forge/trio-asyncio-feedstock: `"created_at": "2019-06-18T17:37:10Z"`
* conda-forge/trio_asyncio-feedstock: `"created_at": "2018-04-27T16:40:01Z"`

The underscore variant got first 😬 That said, there are more `trio-*` packages so maybe for consistency we should keep the dash version? @conda-forge/trio-asyncio @conda-forge/trio_asyncio, please reach an agreement and decide which feedstock will absorb the other one by creating the needed alias output.

Thanks!

**Comment by dhirschfeld** [comment]
> The underscore variant got first 😬

Yes, I almost immediately regretted that! This should perhaps have been a multi-output there, but I'm happy to archive my version in favour of a multi-output here.

**Comment by jaimergp** [comment]
Thanks @dhirschfeld - if you can add the PR (include yourself as a maintainer!), I am sure we can get it merged!

**Comment by dhirschfeld** [comment]
> Thanks @dhirschfeld - if you can add the PR (include yourself as a maintainer!), I am sure we can get it merged!

I'll look to do that when I can find the time, if no one beats me to it...
